name: Feature

on:
  workflow_dispatch:
  push:
    branches:
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: activetheory/build-v8
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate AT Services
        uses: activetheory/hydra-auth-action@v2.2.2
      - name: Restore build cache
        uses: actions/cache@v4
        env:
          cache-name: hydra-deploy-cache
        with:
          path: |
            ~/.npm
            ./node_modules
            ./.hydra
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Get Branch Name
        id: branch_name
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          echo "branch_name=${BRANCH##*/}" >> $GITHUB_OUTPUT
      - name: Install Dependencies
        run: |
          npm i
          npm i @hermes/deploy@0.0.5
      - name: Build
        env:
          APPENGINE_SERVICE_ACCOUNT: ${{ secrets.APPENGINE_SERVICE_ACCOUNT }}
        run: |
            echo $APPENGINE_SERVICE_ACCOUNT > service-account.json
            npx hermes-build dev
      - name: Deploy
        env:
          BRANCH: ${{ steps.branch_name.outputs.branch_name }}
        run: |
          npx hermes-deploy --name google-advocacy-demos-${{ env.BRANCH }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: google-advocacy-demos
          SLACK_COLOR: success
          SLACK_ICON: https://github.com/activetheory.png?size=48
          SLACK_TITLE: "Deployed branch: ${{ github.ref_name }}"
          SLACK_USERNAME: "GitHub Actions"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_FOOTER: "${{ github.ref_name }} | <https://google-advocacy-demos-${{ steps.branch_name.outputs.branch_name }}.activetheory.dev|https://google-advocacy-demos-${{ steps.branch_name.outputs.branch_name }}.activetheory.dev>"
          MSG_MINIMAL: true

